### PR TITLE
[feature] add support for agent orientation

### PR DESCRIPTION
**Pull request by JustinShetty**
These commits:
- extend `Config` to be a set of `Pose`s, which describe location and orientation
- update the input regex to support solutions with and without orientation
- update the draw function to add triangles to both agents and goal markers to show orientation
- add a small orientation demo
- updates the README to point to a newer openframeworks version which works Ubuntu 24
- add the `bin/` directory to the gitignore

### CODE REVIEW

**Comment by JustinShetty** [comment]
If you decide to accept this, please squash the commits 😅

**Comment by Kei18** [comment]
Hey @JustinShetty, could you provide a sample video? This repo's purpose is to provide a simple yet extensible visualiser for MAPF. Adding orientation, source/sink, etc., may be attractive, but I am not sure it aligns with the above purpose just from the code.

**Comment by JustinShetty** [comment]
For what it's worth, the source/sink changes apper in the commit history but I reverted all of those additions. The changes are limited to what I stated in the PR description.

Here is a sample of what this PR adds (`mapf-visualizer assets/2x2.map assets/demo_2x2.txt`)

https://github.com/user-attachments/assets/cda60733-e659-4853-83b6-357198032361

It's completely backwards-compatible with the existing solution format (existing demos work)

**Comment by Kei18** [comment]
OK, thanks! This is cool. I will check the codes in detail and merge them into the main branch later.

**Pull request closed without merging**
